### ISSUE TITLE
Cannot run script because /bin script uses dos line endings

### ISSUE THREAD

**Issue by hilkeheremans** [eberlitz/splashicon-generator#13]
When I downloaded your package it failed to run due to the line endings being dos (\r\n) instead of unix.

This will typically produce the following error on Mac OS X:
```

env: node\r: No such file or directory
```

@Other users, you can fix this by converting the line endings to unix.

**Comment by asierazaceta** [comment]
Let me suggest you to use the `dos2unix` util. You can use 'brew install dos2unix' if you have [homebrew](http://brew.sh/) installed (otherwise.. install it ;-) )

**Comment by hilkeheremans** [comment]
Yes, good idea. Just wanted to drop this here in case someone else had the same issue. It might be worth adding your suggestion to the readme?

**Comment by eberlitz** [comment]
I changed the line ending of the script so it should work now with the published version 0.2.7 in the npm registry.
