### ISSUE TITLE
Possible to set output dir?

### ISSUE THREAD

**Issue by pke** [eberlitz/splashicon-generator#19]
I don't see any option to set the output dir. Is that possible?

**Comment by eberlitz** [comment]
At the moment, files will be generated based on the current working directory.

**Comment by pke** [comment]
It seems not even that, but the directory where package.json is located in when the generator is started via `npm run`. Strange.

**Comment by eberlitz** [comment]
At the moment, using the CLI, files will be generated based on the current working directory. If you require the package you can specify custom icons and platforms with the desired path. Maybe to much work to make that.

**Comment by pke** [comment]
What I mean is that when I start `npm run` from a subfolder, your generator still looks for the icons/and saves the resulting splash/icons in the folder where the package.json is located. Maybe that's a quirks of how npm sets the `cwd`. Any idea?

**Comment by eberlitz** [comment]
Don't know why it's happening. You mean using the npm scripts? Can you send me your package.json file? Maybe I can try your scenario here.

**Comment by pke** [comment]
```
scripts: {
  "prepare:icons": "splashicon-generator --imagespath=base-icons",
}
```

Given that folder structure:
```
/app/package.json
/app/subfolder/base-icons
```

call `npm run prepare:icons` from within `subfolder`. It should use the `base-icons` folder but it is actually looking for `basic-icons` in the same folder where package.json is located in.

**Comment by eberlitz** [comment]
Yes in this case you should use:

`
scripts: {
  "prepare:icons": "splashicon-generator --imagespath=subfolder/base-icons",
}
`

Note that you must include the path of the base icons relative to the current working directory that in the context of the npm is where the package.json is located.

**Comment by pke** [comment]
While this may work, I can't change the scripts command for every subfolder I want to create the icons in (white label app). The question is, why is npm setting the wrong `cwd`.

**Comment by eberlitz** [comment]
This is an NPM behavior. Don't know how to by pass it.

**Comment by pke** [comment]
Why not provide a CLI param for the output folder, which is by default `process.cwd()` if not specified?

This change would also help:
`var filePath = path.join(path.dirname(settings.ICON_FILE), platform.iconsPath, icon.name);`

Then the `res` folders would be created alongside the `ICON_FILE` folder
