### ISSUE TITLE
On Android splash screen is distorted 

### ISSUE THREAD

**Issue by azachar** [eberlitz/splashicon-generator#22]
Hello, 
thank you for your great plugin! I having a some problem with the aspect ratio on Android 5.1+ devices.

Do you plan to fix distortion based on this:  http://stackoverflow.com/questions/23157049/cordova-android-splashscreen-are-distorted
or what is actually a real solution here.

Thank you for your reply.

Best regards,
Andrej

**Comment by eberlitz** [comment]
The sizes mentioned as the solution of the problem in the stackoverflow is already at use. Maybe it's missing the xxhdpi and the xxxhdpi assets. I've just updated the package including those assets. Give it a try, just don't forget to update your config.xml file adding this assets:

```
<platform name="android">
    <splash density="land-xxhdpi" src="res/screens/android/screen-xxhdpi-landscape.png" />
    <splash density="land-xxxhdpi" src="res/screens/android/screen-xxxhdpi-landscape.png" />
    <splash density="port-xxhdpi" src="res/screens/android/screen-xxhdpi-portrait.png" />
    <splash density="port-xxxhdpi" src="res/screens/android/screen-xxxhdpi-portrait.png" />
</platform>
```

**Comment by azachar** [comment]
@eberlitz Thank you very much! I give a try!
