### ISSUE TITLE
Invalid Parameter - -set error

### ISSUE THREAD

**Issue by ryanlin1986** [eberlitz/splashicon-generator#23]
Checking Splash & Icon

  ✓  model\icon.png exists
  ✓  model\splash.png exists

 Generating Icons for ios

{ [Error: Command failed: Invalid Parameter - -set
] timedOut: false, killed: false, code: 4, signal: null }

**Comment by eberlitz** [comment]
Did you install ImageMagick? And is it accessable from your PATH?

**Comment by ryanlin1986** [comment]
![image](https://cloud.githubusercontent.com/assets/11850439/16874891/a8887fda-4ace-11e6-9fb1-d6336d09ea82.png)

Yes The ImageMagic is installed correctly.
What I have installed version file name is: ImageMagick-7.0.2-4-Q16-x64-dll.exe

**Comment by eberlitz** [comment]
Execute this command line in dos:

`where convert`

and paste here the results.

**Comment by ryanlin1986** [comment]
C:\Users\ryanl>where convert
C:\Windows\System32\convert.exe

**Comment by eberlitz** [comment]
This is the problem. It didin't find the image magic "convert" tool and is using the windows convert tool. 

For me I get this:
```bash
λ where convert
C:\Program Files\ImageMagick-6.9.2-Q16\convert.exe
C:\Windows\System32\convert.exe
```

**Comment by ryanlin1986** [comment]
Got it, thanks for the hint, I have to check the following option(which is not enabled by default):
![image](https://cloud.githubusercontent.com/assets/11850439/16875173/92764ef0-4ad0-11e6-9267-50c3707fbdea.png)

Please update the readme to mention about it if you have time;)
