### ISSUE TITLE
Missing some @3x icons for iPhone 6 Plus

### ISSUE THREAD

**Issue by dharders** [eberlitz/splashicon-generator#25]
I found when using cordova with an iOS target platform and testing with my iPhone 6 plus, the default cordova icon would show up when a 'double tap' of the home button occurs. All other icons seem to work (i.e. Home icon, Search/Spotlight etc).

I used your `config.xml` as stated in your docs.

Not sure if this is strictly an iPhone 6+ issue or iOS 9+ issue, either way, I have solved it below.

I fixed my issue by modifying `index.js` [#L33-L48](https://github.com/eberlitz/splashicon-generator/blob/master/index.js#L33-L48) to add a `-3x` for all icons  and increased the respective `size:`

I also updated `config.xml` to point to these new files. 

Please update the repo so other iPhone 6+ users don't run into the same issue.

Thanks again for creating such a handy tool!

**Comment by pke** [comment]
Care to submit a PR with your changes?

**Comment by dharders** [comment]
@pke I'll see what I can do later this week...pretty swamped with work currently!

**Comment by dharders** [comment]
@pke Fixed in #26

**Comment by pke** [comment]
Great. Thanks!

**Comment by dharders** [comment]
@eberlitz good to close this issue, since merged. Or wait for npm release ?

**Comment by eberlitz** [comment]
Hi, thanks for your work. I just validate the sizes with the Apple docs and removed the unused ones to not increase the size of the app without need.

Also included the new splash sizes for the iPad Pro 12.9".

Released under npm as 0.2.10;
