### ISSUE TITLE
Use lwip instead of imagemagick

### ISSUE THREAD

**Issue by pke** [eberlitz/splashicon-generator#27]
~~I wonder what you think about using SVGs as source images for icons and splash?
That would eliminate the need for big PNGs and "save areas" as SVGs can be scaled very well.
**edit** Hmmm. I just see that lwip does not support loading SVG atm :(~~

What about using https://www.npmjs.com/package/lwip instead of imagemagick?
Its lightweight, doesn't need no installation on any platform (would come as a dependency of this package).

**Comment by eberlitz** [comment]
My intentions was to change to GraphicsMagick. But I will check this lwip.

**Comment by pke** [comment]
Anything that reduces external dependencies would be fine :)

**Comment by peterschmidler** [comment]
also, the imagemagick module seems abandoned, throws ugly "resize arg" console.logs and fails on some machines with an "Error: spawn convert ENOENT" error...

**Comment by pke** [comment]
aha. I already wondered where those "resize arg" output originated from. Yeah, I think reducing one dependency would be a nice effort.

I also thought if it would be possible, when using SVG as the input, to actually be able to have text in them and with SVG/CSS to position this text. That would allow us to get rid of the "safe-areas" and the rendered PNG output would always look great on all resolutions.

**Comment by pke** [comment]
And by the way, we could also support SVG as the source format: https://github.com/domenic/svg2png

**Comment by lcaprini** [comment]
@pke @peterschmidler In my fork I removed ImageMagick and I'm using GraphicsMagick; same code and same functionalities. Here the PR: [https://github.com/eberlitz/splashicon-generator/pull/45](https://github.com/eberlitz/splashicon-generator/pull/45).

-L
