### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by AEtherSurfer** [eberlitz/splashicon-generator#3]
$ splashicon-generator
env: node\r: No such file or directory

**Comment by eberlitz** [comment]
Fixed in https://github.com/eberlitz/splashicon-generator/commit/0ff762f1ab97962101db67231fb363689ce99a2f

**Comment by RobIsHere** [comment]
I see this bug in the current version 0.2.11 on osx

**Comment by pwkrile** [comment]
^same here

**Comment by eberlitz** [comment]
Corrected on 0.2.12
