### ISSUE TITLE
Execution fails on Linux due to CRLF line endings

### ISSUE THREAD

**Issue by jacksenechal** [eberlitz/splashicon-generator#32]
After installing via npm, running `splashicon-generator` on Linux fails with

> /usr/bin/env: ‘node\r’: No such file or directory

And an inspection of `node_modules/splashicon-generator/bin/splashicon-generator` shows that line endings are CRLF. Changing it to LF, everything is good.

**Comment by eberlitz** [comment]
New version published to NPM
