### ISSUE TITLE
Support xxhdpi and xxxhdpi on Android.

### ISSUE THREAD

**Issue by networksolution** [eberlitz/splashicon-generator#4]
Hi. I see you're supporting iPhone 6 and iPhone 6 Plus. May you add support for xxhdpi and xxxhdpi on Android too? In other tools I saw this is available.

Also you should update your documentation here https://www.npmjs.com/package/splashicon-generator and here https://github.com/eberlitz/splashicon-generator because you're saying you support only iOS and Android, but you're actually supporting Windows Phone 8 too

**Comment by eberlitz** [comment]
The icons for xxhdpi and xxxhdpi are generated. But I think that the PhoneGap Build Ignore them.

I updated the documentation including the windows phone 8 support, thanks

**Comment by networksolution** [comment]
I was referring to splash screens, not icons

**Comment by ronaldjeremy** [comment]
+1, the splash screens on the galaxy note 3 (which is xxhdpi) come out distorted, not sure if that is because there is no xxhdpi splash generated or not...

**Comment by eberlitz** [comment]
Looking around I found this (http://stackoverflow.com/questions/13487124/android-splash-screen-sizes-for-ldpi-mdpi-hdpi-xhdpi-displays-eg-1024x76/27125893#27125893), which suggests the use of 9-patch for xxhdpi and xxxhdpi.

I'll investigate how can I implement that in the future. Don't have much time right now.

**Comment by ManuelOverdijk** [comment]
Any update on this? Would be a really nice to have

**Comment by eberlitz** [comment]
Nope, but PR's are welcome.

**Comment by eberlitz** [comment]
New realease 0.2.8 with this #21
