### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by eiriksm** [eberlitz/splashicon-generator#6]
Hey. 

Thanks for this very useful module!

Not sure why (since looking at the commit history would suggest otherwise), but I am still getting the error in #3 when installing 0.1.5.

If I try to install it from github I get the correct version (with unix line breaks). Also, if I convert to unix line breaks, everything works again.

Confirmed this issue on both linux and mac os x. 

The only possible explanation I can see is if you manually published a new version from your working directory, without the actual changes made (only the one in package.json).

Do you think you can publish a new version, to see if that fixes the issue? Also, of course, it has the added bonus of updating the project description (per readme) on npmjs.org with the latest change. :)

Thanks again for making this, and have a great day!

**Comment by eberlitz** [comment]
Hi, i've just published a new version on npm. I tested it on a Mac OS and it now works fine.

**Comment by eiriksm** [comment]
I can verify that, thanks!
